### ISSUE TITLE
SLOWFAST_4x16_R50.yaml file

### ISSUE THREAD

**Issue by mmi-w-1400** [OpenGVLab/UniFormerV2#3]
Hello, thank you for your excellent work. When i want run `run_net_multi_node.py`, in `parser.py` in line 78 need _configs/Kinetics/SLOWFAST_4x16_R50.yaml_ but this file doesn't exist. How can i make or download this file?

![Screenshot from 2022-11-23 11-02-37](https://user-images.githubusercontent.com/118332143/203492872-01805490-94a3-47c1-8729-95bb6f016899.png)

**Comment by Andy1621** [comment]
Since the codebase is followed [SlowFast](https://github.com/facebookresearch/SlowFast), the default path of `cfg_file` is `configs/Kinetics/SLOWFAST_4x16_R50.yaml`.

You can simply follow the step in [INSTRUCTION](https://github.com/OpenGVLab/UniFormerV2/blob/main/INSTRUCTIONS.md).
For example, run the following code
```shell
bash ./exp/k400/k400_b16_f8x224/run.sh
```
It will set the `cfg_file` via `--cfg_file`.
<img width="440" alt="image" src="https://user-images.githubusercontent.com/24236723/203509992-468bd8cf-7fdf-4cd2-b2b8-cd488de0ee55.png">

**Comment by mmi-w-1400** [comment]
Thanks.
